language: scala
scala:
- 2.11.12
jdk:
- oraclejdk8
before_deploy:
  - pip install --user release-manager==0.3.0
deploy:
  - provider: script
    script: ./.travis/deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      tags: true
env:
  global:
  - secure: UqZib6Nd69EMAI3VIg2A6lbwpfqDuZyoQM4UPCGWjSEGTKjybn/yharWGhHDHUWp2JCO+rBpPVH6lKf2INtwP4BR96NR4FpRfOlXcVpTljXsy36XZ+vzOupUj5OwgbJwMI8ZRJ2ii/zlZLO57hXLuyB6b6uq6VqX0LzYwyhYcD+5qgmNxZFveVtvrfFZV/Btz78EcjjJ/JZOs7bNl393k2UnxCVVETnhXV2I5cjqunPFvNT1cY3aNBc9uV4VwbhEmQBHsH4GUrrqIT9Y1nx62VrZLnXKHLIu/RVHX9VduwJ7S48/SJFBzCsUbqsN/oHvgK6tya+y3ASCpTfIBDL7/VX2wPcmkJKWkjEIMTrgyQ21sjNsFQABfSNnciTa6k3SWUljaGu9KL5M9l/FvhIq5E7NgIWxXw28n4kmyhBvrPGl+hFTejRVOXhQ7OCXNqDdhEdR/pwHChXK3QVckLMOXB1oNjDaW8oQAKlhN4YJYd09BOzSv679C6oXViEXop3EykPosKNEIcc4PuwFPLKHO90sZc9jaW18eCkUD0U+zyzSL0gC+irG9txXGVZgKtsvYA+NQoJE23eMpkIIrAgLl51lEKas5YFzNaJdQPi0v2QH2U2AZLIMnu13IcBNNpXvQCWd5EsPSwGrS3kw2zXqqqx/fS02bjouHP0cPN4WFDM=
  - secure: 5iZpYGn5EzsJViP7b9ikfz0NrMM19UIfW7HWqi6xeHwD0hZEhcUK+PVg11L45Hrn2JrrbKDbfHQ1yVxm5ByHzJEGhSylid3OZkLazCuAvgG2aRS0QSZPeGQUiSVGie2lc5m5sDfhpIjtUTf+u2gW+wjMdoxYILpfLUdo92nGYtZiUc3AOgkA/r1HljAnq92FtRZbiHrWeY8pewxDQHdmcwGTWfwMHhXL4suK+geD5by+r1hmI/j1IpeRG8Rj4F4bcWaMfjKby49f3Kwlo41crkOvd39YnkABa5Yjy0c1kW/t8HY7MoejkwfnuCgNUGMS05jiaAnke1zbxGZFBBqx7nvDWICU46behIz0onEH5/BLo2oLzIA8oeZEv6Oj7jf0d5KIxJE7B0FWZznnS9I20aL2UeNkopgx6f6a2z8bQJQ8wPnc76hlRJbtjlJVkUxQoYXgPnpchJxdDugV5FZ3KdSV4gW+kVsQ/ZAJIwzxI3tl8lu5QY5iqe9+/SPlD+o83DnYxq+rUkjLGzIT3LuLlEoHh/9mieQs3cHfyyNhxAuJqV1nws1BpgHYVTJbvHQm0uGcid8Z2PRcIJrTN3UZaPHn2AprCzVFxkkJw5m5i5Wgr7axNtTK/o+yX20pdJBl3oBKX5234zQLeEE7/XcDZ1c2Mye9lPIllV5xzc44IYc=
